Repository x1-company/be14-4th-x1-GROO-FE, pull requests merged in 2025-05, with the labels that each got.

#23 🌟 feat: 방명록 조회 및 작성 수정
  src/components/GuestbookList.vue
  src/components/SideMenu.vue
  src/router/index.js
Labels: ✨ Feature

#20 🔨 fix: 공개 여부 DB와 반대로 뜨는 오류 해결
  src/components/SideMenu.vue
  src/views/ForestDetail.vue
Labels: 🚑 fix

#27 🌟 일기 작성 및 분석 결과 화면 백 api 연동
  package-lock.json
  package.json
  src/components/AnalyzeResult.vue
  src/components/CategorySelector.vue
  src/components/SideMenu.vue
  src/components/WriteDiary.vue
  src/icons/annoy_icon.png
  src/icons/annoy_icon_cat.png
  src/icons/anxious_icon.png
  src/icons/joy_icon.png
  src/icons/joy_icon_cat.png
  src/icons/melancholy_icon.png
  src/icons/melancholy_icon_cat.png
  src/icons/peaceful_icon.png
  src/icons/peaceful_icon_cat.png
  src/icons/romanc_icon_cat.png
  src/icons/romance_icon.png
  src/icons/sad_icon.png
  src/icons/sad_icon_cat.png
  src/icons/tired_icon.png
  src/icons/tired_icon_cat.png
  src/services/api.js
Labels: ✨ Feature

#29 🌟 feat: 일기 작성 화면 날짜 추가해서 백엔드 api 연동 완료
  src/components/WriteDiary.vue
  src/services/api.js
Labels: ✨ Feature

#33 🌟 feat: 방명록 상세보기 기능 구현
  src/components/GuestBookDetail.vue
  src/components/GuestbookList.vue
  src/components/SideMenu.vue
  src/components/WriteGuestbook.vue
  src/icons/previous_icon2.png
  src/views/ForestDetail.vue
Labels: ✨ Feature

#34 🔨 fix: 충돌 병합 중 발생한 오류 수정
  src/components/SideMenu.vue
Labels: 🚑 fix

#39 오류수정완료
  src/App.vue
  src/components/ConfirmModal.vue
  src/components/SideMenu.vue
  src/main.js
Labels: 🚑 fix

#40 🌟 feat: 우정의 숲 다시보기, 우리의 조각 보기 구현
  src/components/DiaryCalendar.vue
  src/components/DiaryDetail.vue
  src/components/ItemList.vue
  src/components/MateSideMenu.vue
  src/components/MyItemView.vue
  src/icons/arrow_back.png
  src/icons/arrow_forward.png
  src/icons/back.png
  src/icons/bird.png
  src/icons/object_icon.png
  src/icons/plant_icon.png
  src/icons/tree.png
Labels: ✨ Feature

#42 🌟 feat: 안개, 꽃비 컴포넌트에 추가 완료
  src/components/FlowerRainEffect.vue
  src/components/FogEffect.vue
Labels: ✨ Feature

#43 🌟 feat: 우정의 숲 아이콘 제거
  src/views/ForestMate.vue
Labels: ✨ Feature

#45 🌟 feat: 우정의 숲 배치 수정
  src/components/DiaryCalendar.vue
  src/components/DiaryDetail.vue
Labels: ✨ Feature

#49 feat: 화면 꾸미기 & 코드 수정
  src/components/ForestListModal.vue
  src/icons/forest1.png
  src/views/InviteCodeView.vue
Labels: ✨ Feature

#53 Feature/jiwon/myitem
  src/components/AnalyzeResult.vue
  src/components/SideMenu.vue
  src/router/index.js
Labels: ✨ Feature

#55 Feature/jiwon/myitem
  src/components/MateSideMenu.vue
  src/components/SideMenu.vue
  src/components/WithdrawModal.vue
Labels: ✨ Feature

#57 🌟 feat: 연필 버튼 눌러서 숲의 이름 수정 기능 구현
  src/components/EditForestName.vue
  src/views/ForestDetail.vue
Labels: ✨ Feature

#58 🌟 feat: 랜딩페이지 섬 크기 조절
  src/views/LandingPage.vue
Labels: ✨ Feature

#59 🌟 feat: 우정의 숲에 일기 작성 기능 추가
  index.html
  src/components/ForestView.vue
  src/components/MateSideMenu.vue
Labels: ✨ Feature

#61 🔨 fix: 몇 개의 날씨 component 수정 및 확정
  index.html
  src/components/FogEffects.vue
  src/components/ForestView.vue
  src/components/YellowDustEffects.vue
  src/views/ForestDetail.vue
Labels: ✨ Feature, 🔨 Refactor

#62 🌟 feat: 모달 창 전체 적용
  src/components/AlertModal.vue
  src/components/BackgroundImage2.vue
  src/components/EditForestName.vue
  src/components/ForestListModal.vue
  src/components/Login.vue
  src/components/MateSideMenu.vue
  src/components/SideMenu.vue
  src/components/Signup.vue
  src/components/WithdrawModal.vue
  src/components/WriteDiary.vue
  src/components/WriteGuestbook.vue
  src/views/InviteCodeView.vue
Labels: ✨ Feature

#63 🌟 feat: 배치완료 버튼 위치 변경
  src/views/ForestDetail.vue
Labels: ✨ Feature
